export const routes = {
  home: "/homepage",
  login: "/login",
  studentDashboard: "/student/dashboard",
  questions: "/questions",
  question: (questionId = ":questionId") => `/questions/${questionId}`,
  mentors: "/mentors",
  mentor: (mentorId = ":mentorId") => `/mentors/${mentorId}`,
  bookingNew: "/bookings/new",
  booking: (bookingId = ":bookingId") => `/bookings/${bookingId}`,
  session: (sessionId = ":sessionId") => `/sessions/${sessionId}`,
  feedback: (bookingId = ":bookingId") => `/bookings/${bookingId}/feedback`,
  review: (bookingId = ":bookingId") => `/bookings/${bookingId}/review`,
  jobDescriptionNew: "/job-descriptions/new",
  jobDescriptionReview: (jobDescriptionId = ":jobDescriptionId") =>
    `/job-descriptions/${jobDescriptionId}/review`,
  jobDescriptionMapping: (jobDescriptionId = ":jobDescriptionId") =>
    `/job-descriptions/${jobDescriptionId}/mapping`,
  preparationPlan: (planId = ":planId") => `/preparation-plans/${planId}`,
  mentorOnboarding: "/mentor/onboarding",
  mentorVerification: "/mentor/verification",
  mentorProfile: "/mentor/profile",
  mentorAvailability: "/mentor/availability",
  mentorBookings: "/mentor/bookings",
  mentorBooking: (bookingId = ":bookingId") => `/mentor/bookings/${bookingId}`,
  mentorSession: (sessionId = ":sessionId") => `/mentor/sessions/${sessionId}`,
  mentorFeedback: (bookingId = ":bookingId") => `/mentor/feedback/${bookingId}`,
  adminQueue: "/admin",
  adminMentorReview: (mentorId = ":mentorId") => `/admin/mentors/${mentorId}/review`,
  adminQuestions: "/admin/questions",
  adminCase: (caseId = ":caseId") => `/admin/cases/${caseId}`,
  adminAudit: (decisionId = ":decisionId") => `/admin/audit/${decisionId}`,
  systemStatus: "/system-status",
} as const;
