import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQuery } from "@tanstack/react-query";
import { useForm } from "react-hook-form";
import { useNavigate, useSearchParams } from "react-router-dom";
import { z } from "zod";
import { bookingsApi, mentorsApi, preparationPlansApi, jobDescriptionsApi } from "@/shared/api/resources";
import AuthNavbar from "@/shared/components/AuthNavbar";
import ErrorPanel from "@/shared/components/ErrorPanel";

const schema = z.object({ context: z.string().min(1, "Chọn JD hoặc kế hoạch"), interviewType: z.string().min(2, "Chọn loại phỏng vấn"), goal: z.string().trim().min(10, "Mục tiêu cần ít nhất 10 ký tự") });
type Values = z.infer<typeof schema>;
export default function BookingNew() {
  const [params] = useSearchParams(); const mentorId = params.get("mentorId") ?? ""; const slotId = params.get("slotId") ?? "";
  const navigate = useNavigate();
  const mentor = useQuery({ queryKey: ["mentor", mentorId], queryFn: () => mentorsApi.get(mentorId), enabled: Boolean(mentorId) });
  const plans = useQuery({ queryKey: ["plans"], queryFn: preparationPlansApi.list });
  const jds = useQuery({ queryKey: ["job-descriptions"], queryFn: jobDescriptionsApi.list });
  const form = useForm<Values>({ resolver: zodResolver(schema), defaultValues: { context: "", interviewType: "Technical Interview", goal: "" } });
  const mutation = useMutation({ mutationFn: (values: Values) => { const [kind, id] = values.context.split(":"); return bookingsApi.create({ mentorId, slotId, goal: values.goal, interviewType: values.interviewType, timezone: Intl.DateTimeFormat().resolvedOptions().timeZone, ...(kind === "plan" ? { preparationPlanId: id } : { jobDescriptionId: id }) }); }, onSuccess: (booking) => navigate(`/bookings/${booking.id}`, { replace: true }) });
  const slot = mentor.data?.nextSlots.find((item) => item.id === slotId);
  if (!mentorId || !slotId) return <div className="min-h-screen bg-canvas"><AuthNavbar /><main className="mx-auto max-w-xl px-6 py-12"><ErrorPanel error={new Error("Missing mentor or slot")} /></main></div>;
  return <div className="min-h-screen bg-canvas"><AuthNavbar /><main className="mx-auto max-w-[800px] px-6 py-8"><h1 className="text-[22px] font-semibold text-ink">Gửi yêu cầu đặt lịch</h1><p className="mt-1 text-sm text-ink-secondary">Mentor chỉ nhận corrected text, topic/question group và mục tiêu tối thiểu.</p>{mutation.error && <div className="mt-5"><ErrorPanel error={mutation.error} /></div>}<form onSubmit={form.handleSubmit((value) => mutation.mutate(value))} className="mt-6 space-y-5 rounded-xl border border-edge bg-panel p-6"><div className="rounded-lg bg-canvas-subtle p-4 text-sm"><strong>{mentor.data?.displayName ?? "Đang tải mentor…"}</strong><p className="mt-1 text-xs text-ink-muted">{slot ? new Date(slot.startsAt).toLocaleString("vi-VN") : "Slot đang được kiểm tra"}</p></div><label className="block text-xs font-semibold text-ink-secondary">Ngữ cảnh chuẩn bị<select {...form.register("context")} className="mt-1.5 w-full rounded-lg border border-edge bg-canvas px-3 py-2.5 text-sm"><option value="">Chọn một mục</option>{plans.data?.items.map((plan) => <option key={plan.id} value={`plan:${plan.id}`}>Kế hoạch {plan.id.slice(0, 8)} · {plan.matchingVersion}</option>)}{jds.data?.items.filter((jd) => jd.status === "CONFIRMED" || jd.status === "ANALYZED").map((jd) => <option key={jd.id} value={`jd:${jd.id}`}>JD {jd.id.slice(0, 8)} · {jd.status}</option>)}</select>{form.formState.errors.context && <span className="mt-1 block text-xs text-danger">{form.formState.errors.context.message}</span>}</label><label className="block text-xs font-semibold text-ink-secondary">Loại phỏng vấn<select {...form.register("interviewType")} className="mt-1.5 w-full rounded-lg border border-edge bg-canvas px-3 py-2.5 text-sm"><option>Technical Interview</option><option>Behavioral</option><option>System Design</option></select></label><label className="block text-xs font-semibold text-ink-secondary">Mục tiêu<textarea rows={4} {...form.register("goal")} className="mt-1.5 w-full rounded-lg border border-edge bg-canvas p-3 text-sm" />{form.formState.errors.goal && <span className="mt-1 block text-xs text-danger">{form.formState.errors.goal.message}</span>}</label><div className="rounded-lg border border-edge bg-canvas-subtle p-4 text-xs leading-5 text-ink-secondary">Tự hủy/đổi lịch khi còn ≥12 giờ. Tối đa hai đề xuất đổi lịch. No-show chỉ báo sau 15 phút và cần xác nhận.</div><button disabled={mutation.isPending || !slot} className="w-full rounded-lg bg-primary px-5 py-3 text-sm font-medium text-on-primary disabled:opacity-50">Gửi yêu cầu</button></form></main></div>;
}
