import { useQuery } from "@tanstack/react-query";
import { Link, useParams } from "react-router-dom";
import { useApp } from "@/app/AppContext";
import { mentorsApi } from "@/shared/api/resources";
import AuthNavbar from "@/shared/components/AuthNavbar";
import PublicNavbar from "@/shared/components/PublicNavbar";
import ErrorPanel from "@/shared/components/ErrorPanel";

export default function MentorProfilePage() {
  const { mentorId = "" } = useParams();
  const { role } = useApp();
  const mentor = useQuery({ queryKey: ["mentor", mentorId], queryFn: () => mentorsApi.get(mentorId), enabled: Boolean(mentorId) });
  return <div className="min-h-screen bg-canvas">{role === "public" ? <PublicNavbar /> : <AuthNavbar />}<main className="mx-auto max-w-[900px] px-6 py-8">{mentor.error ? <ErrorPanel error={mentor.error} onRetry={() => mentor.refetch()} /> : mentor.isLoading ? <p className="text-sm text-ink-muted">Đang tải hồ sơ…</p> : mentor.data && <><section className="rounded-xl border border-edge bg-panel p-7"><div className="flex items-start gap-5"><div className="grid h-16 w-16 place-items-center rounded-full bg-primary-soft text-lg font-semibold text-primary">{mentor.data.displayName.slice(0, 2).toUpperCase()}</div><div><h1 className="text-xl font-semibold text-ink">{mentor.data.displayName}</h1><p className="mt-1 text-sm text-ink-secondary">{mentor.data.headline}</p><p className="mt-1 text-xs text-ink-muted">Đã xác minh · {mentor.data.timezone} · rating {mentor.data.publicRating ?? "Chưa có"}</p></div></div><p className="mt-6 whitespace-pre-wrap text-sm leading-7 text-ink-secondary">{mentor.data.bio}</p><div className="mt-4 flex flex-wrap gap-2">{mentor.data.expertise.map((topic) => <span key={topic} className="rounded-full bg-primary-soft px-3 py-1 text-xs text-primary">{topic}</span>)}</div></section><section className="mt-6"><h2 className="text-sm font-semibold text-ink">Khung giờ còn trống</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{mentor.data.nextSlots.map((slot) => <article key={slot.id} className="rounded-xl border border-edge bg-panel p-4"><p className="text-sm font-medium text-ink">{new Date(slot.startsAt).toLocaleString("vi-VN")}</p><p className="mt-1 text-xs text-ink-muted">{slot.timezone} · {Math.round((new Date(slot.endsAt).getTime() - new Date(slot.startsAt).getTime()) / 60000)} phút</p>{role === "student" ? <Link to={`/bookings/new?mentorId=${mentor.data!.id}&slotId=${slot.id}`} className="mt-3 inline-block rounded-md bg-primary px-4 py-2 text-xs font-medium text-on-primary">Chọn slot</Link> : <Link to="/login" className="mt-3 inline-block text-xs font-medium text-primary">Đăng nhập để đặt lịch</Link>}</article>)}{mentor.data.nextSlots.length === 0 && <p className="text-sm text-ink-muted">Mentor chưa mở slot tương lai.</p>}</div></section><section className="mt-8"><h2 className="text-sm font-semibold text-ink">Đánh giá đã công khai</h2><div className="mt-3 space-y-3">{mentor.data.reviews?.map((review) => <article key={review.id} className="rounded-xl border border-edge bg-panel p-4"><div className="flex items-center justify-between gap-3"><p className="text-sm font-medium text-ink">{review.studentName}</p><p className="text-xs font-semibold text-primary">{review.rating}/5</p></div>{review.comment && <p className="mt-2 text-sm leading-6 text-ink-secondary">{review.comment}</p>}<p className="mt-2 text-xs text-ink-muted">{new Date(review.createdAt).toLocaleDateString("vi-VN")}</p></article>)}{!mentor.data.reviews?.length && <p className="text-sm text-ink-muted">Chưa có đánh giá được công khai.</p>}</div></section></>}</main></div>;
}
