/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["rotateCsrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/accept-admin-invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acceptAdminInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStudentProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateStudentProfile"];
        trace?: never;
    };
    "/taxonomy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTaxonomy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{questionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        get: operations["getQuestion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice-progress/{questionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["updatePracticeProgress"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListQuestions"];
        put?: never;
        post: operations["createQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/questions/{questionId}/lifecycle": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["changeQuestionLifecycle"];
        trace?: never;
    };
    "/job-descriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listJobDescriptions"];
        put?: never;
        post: operations["createJobDescription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/job-descriptions/{jobDescriptionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobDescriptionId: components["parameters"]["JobDescriptionId"];
            };
            cookie?: never;
        };
        get: operations["getJobDescription"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/job-descriptions/{jobDescriptionId}/extract": {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                jobDescriptionId: components["parameters"]["JobDescriptionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startExtraction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/job-descriptions/{jobDescriptionId}/extraction-retries": {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                jobDescriptionId: components["parameters"]["JobDescriptionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retryExtraction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/job-descriptions/{jobDescriptionId}/text": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobDescriptionId: components["parameters"]["JobDescriptionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["saveCorrectedText"];
        trace?: never;
    };
    "/job-descriptions/{jobDescriptionId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobDescriptionId: components["parameters"]["JobDescriptionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmCorrectedText"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/job-descriptions/{jobDescriptionId}/analyze": {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                jobDescriptionId: components["parameters"]["JobDescriptionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["analyzeJobDescription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/job-descriptions/{jobDescriptionId}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobDescriptionId: components["parameters"]["JobDescriptionId"];
            };
            cookie?: never;
        };
        get: operations["getJobDescriptionAnalysis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/job-descriptions/{jobDescriptionId}/requirement-normalizations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobDescriptionId: components["parameters"]["JobDescriptionId"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["saveRequirementNormalizations"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/job-descriptions/{jobDescriptionId}/matches": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobDescriptionId: components["parameters"]["JobDescriptionId"];
            };
            cookie?: never;
        };
        get: operations["getMatches"];
        put?: never;
        post: operations["createMatches"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preparation-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPreparationPlans"];
        put?: never;
        post: operations["createPreparationPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preparation-plans/{planId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: components["parameters"]["PlanId"];
            };
            cookie?: never;
        };
        get: operations["getPreparationPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mentors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMentors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mentors/{mentorId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mentorId: components["parameters"]["MentorId"];
            };
            cookie?: never;
        };
        get: operations["getMentor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mentor-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMentorProfile"];
        put: operations["saveMentorProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mentor-verifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitMentorVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/availability-slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAvailabilitySlots"];
        put?: never;
        post: operations["createAvailabilitySlot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/availability-slots/{slotId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slotId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["cancelAvailabilitySlot"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/mentor-verifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMentorVerifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/mentor-verifications/{verificationId}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                verificationId: string;
            };
            cookie?: never;
        };
        get: operations["getMentorEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/mentor-verifications/{verificationId}/evidence-link": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                verificationId: string;
            };
            cookie?: never;
        };
        get: operations["createMentorEvidenceLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/mentor-verifications/{verificationId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                verificationId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["decideMentorVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBookings"];
        put?: never;
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{bookingId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        get: operations["getBooking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{bookingId}/transitions": {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["transitionBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{bookingId}/meeting-link": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["saveMeetingLink"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{bookingId}/meeting-link-failures": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reportMeetingLinkFailure"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{bookingId}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        get: operations["getFeedback"];
        put?: never;
        post: operations["createFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{bookingId}/feedback/apply": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["applyFeedbackToPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{bookingId}/review": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["readNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/operation-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOperationCases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/operation-cases/{caseId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        get: operations["getOperationCase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/operation-cases/{caseId}/impact": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        get: operations["previewOperationImpact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/operation-cases/{caseId}/actions": {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                caseId: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["actOnOperationCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAuditLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Recovery: {
            /** @enum {string} */
            kind: "RETRY_SAFE" | "EDIT_INPUT" | "REUPLOAD" | "PASTE_TEXT" | "SELECT_ANOTHER_SLOT" | "WAIT" | "CONTACT_SUPPORT" | "NONE";
            retryable: boolean;
            retryAfterSeconds: number | null;
        };
        Error: {
            code: string;
            message: string;
            /** Format: uuid */
            correlationId: string;
            fieldErrors: {
                [key: string]: string;
            };
            recovery: components["schemas"]["Recovery"];
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            status?: string;
            roles: ("STUDENT" | "MENTOR" | "ADMIN")[];
        };
        RegisterInput: {
            /** Format: email */
            email: string;
            password: string;
            displayName: string;
        };
        LoginInput: {
            /** Format: email */
            email: string;
            password: string;
        };
        TokenInput: {
            token: string;
        };
        /** @enum {string} */
        Difficulty: "EASY" | "MEDIUM" | "HARD";
        Question: {
            /** Format: uuid */
            id: string;
            slug: string;
            title: string;
            content: string;
            answerCriteria?: string[];
            difficulty: components["schemas"]["Difficulty"];
            /** @enum {string} */
            lifecycleStatus: "DRAFT" | "IN_REVIEW" | "PUBLISHED" | "ARCHIVED";
            topics: string[];
            positions: string[];
            version: number;
        };
        JobDescription: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            sourceType: "PASTED_TEXT" | "PDF" | "IMAGE";
            /** @enum {string} */
            status: "DRAFT" | "EXTRACTING" | "READY_FOR_REVIEW" | "CONFIRMED" | "ANALYZED" | "FAILED";
            correctedText?: string | null;
            correctedVersion: number;
            version: number;
        };
        Booking: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            mentorId: string;
            /** Format: uuid */
            slotId: string;
            /** @enum {string} */
            status: "PENDING" | "CONFIRMED" | "RESCHEDULE_PROPOSED" | "REJECTED" | "CANCELLED" | "COMPLETED" | "NO_SHOW";
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            version: number;
        };
        PageInfo: {
            page: number;
            pageSize: number;
            total: number;
        };
    };
    responses: {
        /** @description Successful resource response */
        Success: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Paginated response */
        Page: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    items: {
                        [key: string]: unknown;
                    }[];
                    pageInfo: components["schemas"]["PageInfo"];
                };
            };
        };
        /** @description Safe actionable error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Safe user projection */
        User: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["User"];
            };
        };
        /** @description Authenticated session */
        Login: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    user: components["schemas"]["User"];
                    csrfToken: string;
                };
            };
        };
        /** @description Question resource */
        Question: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Question"];
            };
        };
        /** @description Question page */
        QuestionPage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    items: components["schemas"]["Question"][];
                    pageInfo: components["schemas"]["PageInfo"];
                };
            };
        };
        /** @description Private job description projection */
        JobDescription: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["JobDescription"];
            };
        };
        /** @description Booking projection */
        Booking: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Booking"];
            };
        };
    };
    parameters: {
        IdempotencyKey: string;
        QuestionId: string;
        JobDescriptionId: string;
        PlanId: string;
        MentorId: string;
        BookingId: string;
        CaseId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
        };
    };
    readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            503: components["responses"]["Error"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterInput"];
            };
        };
        responses: {
            201: components["responses"]["User"];
            409: components["responses"]["Error"];
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenInput"];
            };
        };
        responses: {
            200: components["responses"]["User"];
            400: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            200: components["responses"]["Login"];
            401: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
        };
    };
    rotateCsrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: components["responses"]["Success"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Password changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
        };
    };
    acceptAdminInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["User"];
            400: components["responses"]["Error"];
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["User"];
            401: components["responses"]["Error"];
        };
    };
    getStudentProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
        };
    };
    updateStudentProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            409: components["responses"]["Error"];
        };
    };
    getTaxonomy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
        };
    };
    listQuestions: {
        parameters: {
            query?: {
                search?: string;
                topic?: string;
                difficulty?: components["schemas"]["Difficulty"];
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["QuestionPage"];
        };
    };
    getQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Question"];
            404: components["responses"]["Error"];
        };
    };
    updatePracticeProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
        };
    };
    adminListQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["QuestionPage"];
        };
    };
    createQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: components["responses"]["Question"];
            422: components["responses"]["Error"];
        };
    };
    changeQuestionLifecycle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Question"];
            409: components["responses"]["Error"];
        };
    };
    listJobDescriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Page"];
        };
    };
    createJobDescription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    text: string;
                };
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            201: components["responses"]["JobDescription"];
            413: components["responses"]["Error"];
            415: components["responses"]["Error"];
        };
    };
    getJobDescription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobDescriptionId: components["parameters"]["JobDescriptionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JobDescription"];
            404: components["responses"]["Error"];
        };
    };
    startExtraction: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                jobDescriptionId: components["parameters"]["JobDescriptionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: components["responses"]["JobDescription"];
            409: components["responses"]["Error"];
        };
    };
    retryExtraction: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                jobDescriptionId: components["parameters"]["JobDescriptionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: components["responses"]["JobDescription"];
        };
    };
    saveCorrectedText: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobDescriptionId: components["parameters"]["JobDescriptionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JobDescription"];
            409: components["responses"]["Error"];
        };
    };
    confirmCorrectedText: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobDescriptionId: components["parameters"]["JobDescriptionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JobDescription"];
            409: components["responses"]["Error"];
        };
    };
    analyzeJobDescription: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                jobDescriptionId: components["parameters"]["JobDescriptionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
        };
    };
    getJobDescriptionAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobDescriptionId: components["parameters"]["JobDescriptionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
        };
    };
    saveRequirementNormalizations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobDescriptionId: components["parameters"]["JobDescriptionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
        };
    };
    getMatches: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobDescriptionId: components["parameters"]["JobDescriptionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
        };
    };
    createMatches: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                jobDescriptionId: components["parameters"]["JobDescriptionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
        };
    };
    listPreparationPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Page"];
        };
    };
    createPreparationPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: components["responses"]["Success"];
        };
    };
    getPreparationPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: components["parameters"]["PlanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            404: components["responses"]["Error"];
        };
    };
    listMentors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Page"];
        };
    };
    getMentor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mentorId: components["parameters"]["MentorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            404: components["responses"]["Error"];
        };
    };
    getMentorProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
        };
    };
    saveMentorProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
        };
    };
    submitMentorVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: components["responses"]["Success"];
            415: components["responses"]["Error"];
        };
    };
    listAvailabilitySlots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Page"];
        };
    };
    createAvailabilitySlot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: components["responses"]["Success"];
            409: components["responses"]["Error"];
        };
    };
    cancelAvailabilitySlot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slotId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Error"];
        };
    };
    listMentorVerifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Page"];
        };
    };
    getMentorEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                verificationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restricted evidence */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    createMentorEvidenceLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                verificationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to a five-minute signed evidence URL */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    decideMentorVerification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                verificationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            409: components["responses"]["Error"];
        };
    };
    listBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Page"];
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: components["responses"]["Booking"];
            409: components["responses"]["Error"];
        };
    };
    getBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Booking"];
            404: components["responses"]["Error"];
        };
    };
    transitionBooking: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Booking"];
            202: components["responses"]["Booking"];
            409: components["responses"]["Error"];
        };
    };
    saveMeetingLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            409: components["responses"]["Error"];
        };
    };
    reportMeetingLinkFailure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: components["responses"]["Success"];
        };
    };
    getFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            404: components["responses"]["Error"];
        };
    };
    createFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: components["responses"]["Success"];
            409: components["responses"]["Error"];
        };
    };
    applyFeedbackToPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
        };
    };
    createReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: components["responses"]["Success"];
            409: components["responses"]["Error"];
        };
    };
    listNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
        };
    };
    readNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
        };
    };
    listOperationCases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Page"];
        };
    };
    getOperationCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
        };
    };
    previewOperationImpact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
        };
    };
    actOnOperationCase: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                caseId: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listAuditLog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Page"];
        };
    };
}
